### ISSUE TITLE
How to tell if this is working

### ISSUE THREAD

**Issue by IanVS** [mschuchard/linter-jenkins#1]
I've just installed this package, and I'm not positive that the linter is able to communicate with my Jenkins host.  What is the best way to check that?  It might be useful to have a command in the command palette which just verifies connectivity, using the package's settings.

**Comment by mschuchard** [comment]
I can add this to the roadmap. For now, if Atom is not throwing any errors to your console that is probably a good sign, but if you have an invalid Jenkinsfile and see no linter errors, that is probably a bad sign.

**Comment by mschuchard** [comment]
Added in efbfe026a2f0ef11337c69cf7537df32fc9520a4. Will be refined before 1.0.3 release.
