### ISSUE TITLE
Curl method doesn't work

### ISSUE THREAD

**Issue by IamBlade** [mschuchard/linter-jenkins#13]
Hi, I am not seeing the debug command in the linter UI even though the file language is detected as Jenkinsfile. If I change the filename to just "Jenkinsfile" I see the debug command then, but it still doesn't provide any error/warnings when I make any file changes.

![Screenshot (38)_LI](https://user-images.githubusercontent.com/45094562/165890602-8d5ac3d5-5519-45de-ac7e-8f1d8ff805c5.jpg)

_with debug command_

![image](https://user-images.githubusercontent.com/45094562/165744981-8b860632-4c8e-4f79-a7c1-01cce1b9d03c.png)
_without debug command_

**Comment by mschuchard** [comment]
In addition to being recognized by Atom as either Jenkinsfile or Groovy language, the filename must contain `Jenkinsfile` in it to exclude non-Jenkinsfile Groovy files. I can modify the code to only require `Jenkinsfile` in the file name if it is recognized as Groovy.

**Comment by mschuchard** [comment]
Resolved in 1ad1825.

**Comment by IamBlade** [comment]
Thanks for the quick response.

The language-jenkinsfile package mentions the scope name as `source.groovy`. But my file grammar says "Jenkinsfile" which is the "name" attribute in the grammar CSON file. So I think your change would actually exclude Jenkinsfiles from being recognised.

Also in the 2nd screenshot attached, my files do have the word "jenkinsfile" in their name, but in lower-case and ideally should be linted. Even in the 1st screenshot, where the case is upper, the info shows the curl request being sent but there are seemingly no error messages, as they should have come. So rather than looking at the filename, wouldn't checking the grammar name work better?

Thanks.
