### ISSUE TITLE
No way of passing credentials to CURL method

### ISSUE THREAD

**Issue by rplevka** [mschuchard/linter-jenkins#6]
there seems to be a missing `Authentication field` for the CURL method section. I can see this field at CLI Methods settings but not at CURL. Perhaps this field might be global to prevent redundancy.

Also I can confirm from the debug output, that the constructed curl command does not contain `-u user:pass`

**Comment by mschuchard** [comment]
According to the documentation, there is no authentication option for the CURL method other than the CSRF. Could you show me where the documentation states otherwise?

**Comment by rplevka** [comment]
https://wiki.jenkins.io/display/JENKINS/Remote+access+API

>Simple example - sending "String Parameters":
>```
>curl -X POST JENKINS_URL/job/JOB_NAME/build \  --user USER:TOKEN \  --data-urlencode json='{"parameter": [{"name":"id", "value":"123"}, {"name":"verbosity", "value":"high"}]}'
>```

I understand that CSRF crumb is needed only if the CSRF is enabled but you still get to authenticate?
(see the above link and navigate to `CSRF Protection` section)

**Comment by mschuchard** [comment]
The documentation previously stated passwords and tokens were only available for the CLI, so something has changed. I will follow up on this.

**Comment by mschuchard** [comment]
I ended up breaking this into three distinct commits 5c236ab8c60ca8d876244d9190b252a72c8fd001 add1bcca7856694fffcd84e05f0cf724a732309a and ce8ae6586bbb3b467b098e70f3c2e80d9fca3a67. Feel free to test this out by 'patching' your locally installed package version with the `lib/main.js` in this repo.
