### ISSUE TITLE
CURL method should enclose the payload in double quotes

### ISSUE THREAD

**Issue by rplevka** [mschuchard/linter-jenkins#7]
Checking the constructed curl command from the debug record, it is apparent that the `-F` option followed by the contains of the dockerfile is not enclosed in double quotes, which breaks the whole command (as it contains spaces).

**Comment by mschuchard** [comment]
The debug setting is for a command to assist with debugging. It is not code. This is also for Jenkins and not Docker, although there is a linter package for that as well. The CURL method currently works for myself and many others.

**Comment by mschuchard** [comment]
As a follow up, I can try to put something in the debug command output for the CURL method to enclose the `Jenkinsfile` content in quotes to make it more shell friendly. In the code, an execution API is leveraged.

**Comment by rplevka** [comment]
you're right, i realized too late. thanks for explaining.
