### ISSUE TITLE
No Feedback

### ISSUE THREAD

**Issue by edobry** [mschuchard/linter-jenkins#9]
I've set up the package using the CURL method and supplied credentials, but I get no feedback whatsoever in regards to whether it is working, or unable to connect to the server. I've installed Linter, checked that the jenkins linter is detected and enabled, and tried enabling debug mode. Is this a bug or am I missing something? Thanks!

**Comment by mschuchard** [comment]
What command does debug mode output in your display?

**Comment by edobry** [comment]
Absolutely nothing; there is no visible difference after installing and configuring this package

**Comment by mschuchard** [comment]
Check for the Atom-Linter icons at the bottom of Atom. Use those to pull up the debug message. If you do not see those, double check the install of Atom-Linter and its associated packages, such as Linter-UI-Default.

**Comment by bvarnai** [comment]
> Check for the Atom-Linter icons at the bottom of Atom. Use those to pull up the debug message. If you do not see those, double check the install of Atom-Linter and its associated packages, such as Linter-UI-Default.

I had the same issue, installing Linter-UI-Default worked. Thanks!

**Comment by jasonmalstrom** [comment]
I'm having the same issue as above. I have the atom linter working for JSON, but I can't get anything to come up for jenkinsfile, even in debug mode, no messages at all.

**Comment by MarkWareham** [comment]
same here. Switching on debug does provide the curl command. Tried the command from terminal. The content of the pipeline isn't escaped properly for the curl to work

**Comment by mschuchard** [comment]
No update in seven months; assuming fixed by installing dependencies as claimed by others. Closing.

**Comment by noldrin** [comment]
I posted above under a different user. The fix was that the plugin works when the filename is Jenkinsfile, and I was expecting it to work for filenames with .groovy extension.
